name: Build and Release bsky-desktop

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: Build bsky-desktop (Linux)
    runs-on: ubuntu-latest
    env:
      ext: ".AppImage"

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup node and npm
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Get npm version action
        id: npmv
        uses: pchynoweth/action-get-npm-version@1.0.1

      - name: Install dependencies
        run: npm install

      - name: Build (x64)
        id: build_package_x64
        run: npm run build -- --arch x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (arm64)
        id: build_package_arm64
        run: npm run build -- --arch arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build bsky-desktop (Windows)
    runs-on: windows-latest
    env:
      ext: ".exe"

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup node and npm
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Get npm version action
        id: npmv
        uses: pchynoweth/action-get-npm-version@1.0.1

      - name: Install dependencies
        run: npm install

      - name: Build (x64)
        id: build_package_x64
        run: npm run build -- --arch x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (arm64)
        id: build_package_arm64
        run: npm run build -- --arch arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build bsky-desktop (macOS)
    runs-on: macos-latest
    env:
      ext: ".dmg"

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup node and npm
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Get npm version action
        id: npmv
        uses: pchynoweth/action-get-npm-version@1.0.1

      - name: Install dependencies
        run: npm install

      - name: Build (x64)
        id: build_package_x64
        run: npm run build -- --arch x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (arm64)
        id: build_package_arm64
        run: npm run build -- --arch arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Get npm version action
        id: npmv
        uses: pchynoweth/action-get-npm-version@1.0.1

      - name: Upload Release
        id: create_release
        uses: qnblackcat/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.npmv.outputs.version }}"
          name: "bsky-desktop v${{ steps.npmv.outputs.version }}"
          files: |
            dist/linux/*.AppImage
            dist/windows/*.exe
            dist/macos/*.dmg