name: Build and Release bsky-desktop

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build bsky-desktop (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: setup node and npm
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Get npm version action
        id: npmv
        uses: pchynoweth/action-get-npm-version@1.0.1

      - name: Install dependencies
        run: npm install

      - name: Compile (For linux)
        id: build_package
        run: npm run build

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.4.3
        with:
          name: bsky-desktop
          path: ${{ github.workspace }}/dist/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: qnblackcat/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Tag_Name
          name: Name
          files: dist/*.appimage